name: FFATourney
version: ${project.version}
main: me.alivesteve.ffatourney.FFATourney
api-version: 1.16
description: FFA tournament for BillyMicMac
authors: [ AliveSteve ]
commands:
  startevent:
    description: Start FFA
    usage: /<command>

  resetevent:
    description: Reset FFA
    usage: /<command>
